apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rdepot-build
spec:
  volumes:
    - name: dockerconfig
      secret:
        secretName: oa-sa-jenkins-registry-config
  containers:
    - name: kaniko
      resources:
        limits:
          memory: "14Gi"
        requests:
          memory: "12Gi"
          cpu: 2
    - name: rdepot-build
      image: registry.openanalytics.eu/openanalytics/rdepot-build:latest
      resources:
        limits:
          memory: "14Gi"
          ephemeral-storage: "30Gi"
          cpu: 7
        requests:
          memory: "12Gi"
          ephemeral-storage: "6Gi"
          cpu: 2
      tty: true
      securityContext:
        privileged: true
      env:
        - name: COMPOSE_HTTP_TIMEOUT
          value: 600
        - name: TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX
          value: registry.openanalytics.eu/proxy/
      imagePullPolicy: Always
      volumeMounts:
        - name: dockerconfig
          mountPath: /root/.docker/config.json
          subPath: data
