apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rdepot-build
spec:
  containers:
    - name: rdepot-build
      image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rdepot-build:latest
      resources:
        limits:
          memory: "8Gi"
          ephemeral-storage: "4Gi"
          cpu: 2
        requests:
          memory: "4Gi"
          ephemeral-storage: "2Gi"
          cpu: 1
      tty: true
      securityContext:
        privileged: true
      env:
        - name: COMPOSE_HTTP_TIMEOUT
          value: 600
