apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rdepot-build
spec:
  containers:
    - name: rdepot-build
      image: registry.openanalytics.eu/openanalytics/rdepot-build:latest
      resources:
        limits:
          memory: "8Gi"
          ephemeral-storage: "8Gi"
          cpu: 2
        requests:
          memory: "6Gi"
          ephemeral-storage: "6Gi"
          cpu: 1
      tty: true
      securityContext:
        privileged: true
      env:
        - name: COMPOSE_HTTP_TIMEOUT
          value: 600
        - name: TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX
          value: registry.openanalytics.eu/proxy/
      imagePullPolicy: Always
