---
api-token:
  secret: SecretKeyToGenJWTsButItShouldBeReplaced

access-token:
  lifetime-default: 30
  lifetime-configurable: true
  length: 32
  allowed-characters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

generate-manuals: true

declarative: false
deleting:
  repositories:
    enabled: true
  packages:
    enabled: true

repository-snapshots: false

default-user-configuration:
  language: en-US
  theme: light
  page-size: 10
  supported-languages:
    - en-US
  supported-themes:
    - light
    - dark

replacing:
  packages:
    enabled: true

# Email related properties
#email:
#  enabled: false
#  password:
#  username:
#  from:
#  smtp:
#    host:
#    port:
#    auth:
#    starttls:

# Authentication related properties
app:
  authentication: simple
  simple:
    users:
      - login: einstein
        password: testpassword
        name: Albert Einstein
      - login: tesla
        password: testpassword
        name: Nicolas Tesla
      - login: galieleo
        password: testpassword
        name: Galileo Galilei
      - login: newton
        password: testpassword
        name: Isaac Newton
      - login: newbie
        password: testpassword
        name: New User
      - login: doe
        password: testpassword
        name: John Doe
    default:
      admins:
        - einstein

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false

message:
  source:
    basename: i18n/messages

entitymanager:
  packages:
    to:
      scan:
        - eu.openanalytics.rdepot.base.entities
        - eu.openanalytics.rdepot.r.entities
        - eu.openanalytics.rdepot.python.entities

# Package upload related properties
package:
  version:
    max-numbers: 10
  upload:
    dir: /opt/rdepot
  rVersions:
    - 3.6
    - 4.0
    - 4.1
    - 4.2
    - 4.3
    - 4.4
    - 4.5
  architectures:
    - x86_64
    - x86
  distributions:
    - centos7
    - centos8
    - rhel9
    - opensuse155
    - focal
    - jammy
    - noble
    - bullseye
    - bookworm
  python:
    hashFunctions:
      - md5
      - sha1
      - sha224
      - sha256
      - sha384
      - sha512

# Repository generation related properties
repository:
  generation:
    dir: /opt/rdepot/generated
  validation-name-regex:
    general: ".+"
    technology:
      python: "[A-Za-z0-9\\-_.~]+"
      r: "[A-Za-z0-9 \\-_.]+"

#spring.mvc.view.prefix=/WEB-INF/pages/
#spring.mvc.view.suffix=.jsp
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    view:
      suffix: .html
  main:
    allow-bean-definition-overriding: true
    log-startup-info: false
  output:
    ansi:
      enabled: always

#Liquibase related properties
  liquibase:
    # change-log: classpath:liquibase-changeLog.xml
    url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
    user: postgres
    password: mysecretpassword
    enabled: true

#spring.devtools.remote.secret=thisismysecret
server:
  error:
    include-stacktrace: never
    path: /error

error:
  whitelabel:
    enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
springdoc:
  pathsToMatch: /api/v2/**
  api-docs:
    path: /v2/api-docs
  swagger-ui:
    path: /docs/api.html
    disable-swagger-default-url: true
    url: /v2/api-docs
    display-query-params: true
  default-produces-media-type: application/json

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-4r [%t] %5p traceId=%X{traceIdMDC} %c{1} : %m %n'
  level:
    liquibase:
      parser: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO

#storage related properties
local-storage:
  max-request-size: 10

storage:
  implementation: local
