api_token:
  secret: SecretKeyToGenJWTsButItShouldBeReplaced
  
generate_manuals: true

declarative: false

repository-snapshots: false

# Email related properties
#email:
#  enabled: false
#  password:
#  username:
#  from:
#  smtp:
#    host:
#    port:
#    auth:
#    starttls:

# Authentication related properties
app:
  authentication: simple
  simple:
    users:
      - login: einstein
        password: testpassword  
        name: Albert Einstein 
      - login: tesla
        password: testpassword
        name: Nicolas Tesla
      - login: galieleo
        password: testpassword
        name: Galileo Galilei
      - login: newton
        password: testpassword
        name: Isaac Newton
      - login: newbie
        password: testpassword
        name: New User
      - login: doe
        password: testpassword
        name: John Doe 
    default:
      admins:
        - einstein

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false

message:
  source:
    basename: i18n/messages

entitymanager:
  packages:
    to:
      scan:
        - eu.openanalytics.rdepot.base.entities
        - eu.openanalytics.rdepot.r.entities

# Package upload related properties
package:
  version:
    max-numbers: 10
  upload:
    dir: /opt/rdepot
    max-file-size: 100000000

# Repository generation related properties
repository:
  generation:
    dir: /opt/rdepot/generated

#spring.mvc.view.prefix=/WEB-INF/pages/
#spring.mvc.view.suffix=.jsp
spring:
  mvc:
    view:
      suffix: .html
  main:
    allow-bean-definition-overriding: true
    log-startup-info: false  

  output:
    ansi:
      enabled: always
        
#Liquibase related properties
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
    url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
    user: rdepot
    password: mysecretpassword
    enabled: true
    
#spring.devtools.remote.secret=thisismysecret
server:
  error:
    include-stacktrace: always
    path: /error
    
error:
  whitelabel:
    enabled: false
  
management:
  metrics:
    web:
      server:
        auto-time-requests: false

springdoc:
  pathsToMatch: /api/**
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /docs/api.html
    disable-swagger-default-url: true
    url: /v1/api-docs
    display-query-params: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO   

#storage related properties
localStorage:
  maxRequestSize: 10

storage:
  implementation: local

requestTimeout: 10
