/**
 * R Depot
 *
 * Copyright (C) 2012-2021 Open Analytics NV
 *
 * ===========================================================================
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Apache License as published by
 * The Apache Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Apache License for more details.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/>
 */
package eu.openanalytics.rdepot.model;

// Generated Jun 24, 2013 12:33:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import eu.openanalytics.rdepot.api.v2.dto.EntityDto;
import eu.openanalytics.rdepot.api.v2.dto.RPackageDto;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", schema = "public")
public class Package implements java.io.Serializable, Comparable<Package>, IEntity<Package>
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8856556003759406171L;
	private int id;
	private String version;
	private Repository repository;
	private User user;
	private Submission submission;
	private String name;
	private String description;
	private String author;
	private String depends = "";
	private String imports = "";
	private String suggests = "";
	private String systemRequirements = "";
	private String license;
	private String title;
	private String url = "";
	private String source;
//	private String referenceManual;
//	private List<String> vignettes;
	private String md5sum;
	
	@Transient
	private Boolean generateManuals;

	@Transient
	public Boolean getGenerateManuals() {
		return generateManuals;
	}

	@Transient
	public void setGenerateManuals(Boolean generateManuals) {
		this.generateManuals = generateManuals;
	}

	private boolean active;
	private boolean deleted = false;
	private Set<PackageEvent> packageEvents = new HashSet<PackageEvent>(0);
	
	@Transient
	private List<Vignette> vignettes;
	
	public Package(Package packageBag)
	{
		this.id = packageBag.id;
		this.repository = packageBag.repository;
		this.user = packageBag.user;
		this.name = packageBag.name;
		this.description = packageBag.description;
		this.author = packageBag.author;
		this.depends = packageBag.depends;
		this.imports = packageBag.imports;
		this.suggests = packageBag.suggests;
		this.systemRequirements = packageBag.systemRequirements;
		this.license = packageBag.license;
		this.url = packageBag.url;
		this.source = packageBag.source;
		this.title = packageBag.title;
		this.md5sum = packageBag.md5sum;
		this.active = packageBag.active;
		this.deleted = packageBag.deleted;
		this.submission = packageBag.submission;
		this.packageEvents = packageBag.packageEvents;
		this.version = packageBag.version;
	}

	public Package()
	{
	}

	public Package(int id, Repository repository, User user, String name,
			String description, String author, String license, String source,
			String title, String md5sum, boolean active, boolean deleted)
	{
		this.id = id;
		this.repository = repository;
		this.user = user;
		this.name = name;
		this.description = description;
		this.author = author;
		this.license = license;
		this.title = title;
		this.source = source;
		this.active = active;
		this.deleted = deleted;
		this.md5sum = md5sum;
	}
	
	public Package(int id, Repository repository, User user, String name,
			String description, String author, String depends, String imports,
			String suggests, String systemRequirements, String license,
			String url, String source, String title, String md5sum, boolean active, boolean deleted,
			Submission submission, Set<PackageEvent> packageEvents)
	{
		this.id = id;
		this.repository = repository;
		this.user = user;
		this.name = name;
		this.description = description;
		this.author = author;
		this.depends = depends;
		this.imports = imports;
		this.suggests = suggests;
		this.systemRequirements = systemRequirements;
		this.license = license;
		this.url = url;
		this.source = source;
		this.title = title;
		this.active = active;
		this.submission = submission;
		this.packageEvents = packageEvents;
		this.deleted = deleted;
		this.md5sum = md5sum;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "version", nullable = false)
	public String getVersion()
	{
		return this.version;
	}

	public void setVersion(String version)
	{
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "repository_id", nullable = false)
	//@JsonManagedReference(value="repository-packages")
	@JsonSerialize(as = IRepositoryProjection.class)
	public Repository getRepository()
	{
		return this.repository;
	}

	public void setRepository(Repository repository)
	{
		this.repository = repository;
	}
		
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "maintainer_id", nullable = false)
	//@JsonManagedReference(value="user-packages")
	@JsonIgnore
	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}
	
	@Column(name = "active", nullable = false)
	public boolean isActive()
	{
		return this.active;
	}

	public void setActive(boolean active)
	{
		this.active = active;
	}
	
	@Column(name = "deleted", nullable = false)
	public boolean isDeleted()
	{
		return this.deleted;
	}

	public void setDeleted(boolean deleted)
	{
		this.deleted = deleted;
	}

	@Column(name = "name", nullable = false)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Column(name = "author", nullable = false)
	public String getAuthor()
	{
		return this.author;
	}

	public void setAuthor(String author)
	{
		this.author = author;
	}

	@Column(name = "depends")
	public String getDepends()
	{
		return this.depends;
	}

	public void setDepends(String depends)
	{
		this.depends = depends;
	}

	@Column(name = "imports")
	public String getImports()
	{
		return this.imports;
	}

	public void setImports(String imports)
	{
		this.imports = imports;
	}

	@Column(name = "suggests")
	public String getSuggests()
	{
		return this.suggests;
	}

	public void setSuggests(String suggests)
	{
		this.suggests = suggests;
	}
	
	@Transient
	public String getFileName() {
		int pathLength = this.source.split("/").length;
		String filename = this.source.split("/")[pathLength - 1];
		return filename;
	}

	@Column(name = "system_requirements")
	public String getSystemRequirements()
	{
		return this.systemRequirements;
	}

	public void setSystemRequirements(String systemRequirements)
	{
		this.systemRequirements = systemRequirements;
	}

	@Column(name = "license", nullable = false)
	public String getLicense()
	{
		return this.license;
	}

	public void setLicense(String license)
	{
		this.license = license;
	}
	
	@Column(name = "title", nullable = false)
	public String getTitle()
	{
		return this.title;
	}
	
	@Column(name = "md5sum", nullable = false)
	public String getMd5sum() 
	{
		return md5sum;
	}

	public void setMd5sum(String md5sum) 
	{
		this.md5sum = md5sum;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	@Column(name = "url")
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "source", nullable = false)
	public String getSource()
	{
		return this.source;
	}

	public void setSource(String source)
	{
		this.source = source;
	}
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "package")
	@OneToOne(fetch = FetchType.EAGER, mappedBy = "package", cascade = CascadeType.REMOVE)
	//@JoinColumn(name = "submission_id", nullable=false)
	//@JsonBackReference(value="package-submissions")
	public Submission getSubmission()
	{
		return this.submission;
	}

	public void setSubmission(Submission submission)
	{
		this.submission = submission;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "package")
	//@JsonBackReference(value="package-events")
	public Set<PackageEvent> getPackageEvents()
	{
		return this.packageEvents;
	}

	public void setPackageEvents(Set<PackageEvent> packageEvents)
	{
		this.packageEvents = packageEvents;
	}
	
	@Override
	public String toString()
	{
		return this.name + " " + this.version;
 	}
	
	@Transient
	public List<Vignette> getVignettes()
	{
		return this.vignettes;
	}

	@Override
	public int compareTo(Package that) 
	{	
		if (!this.name.equals(that.name))
		{
			throw new IllegalArgumentException(
					"Trying to compare package " + that.name + 
					" with package " + this.name + 
					" is like comparing apples with oranges.");
		}
				
		String[] theseSplittedDots = this.version.split("-|\\.");
		String[] thoseSplittedDots = that.version.split("-|\\.");
		int length;
		if(theseSplittedDots.length - thoseSplittedDots.length > 0) {
			length = thoseSplittedDots.length;
		} else {
			length = theseSplittedDots.length;
		}
		
		int thisNumber, thatNumber;
		for(int i = 0; i < length; i++) {
			thisNumber = Integer.parseInt(theseSplittedDots[i]);
			thatNumber = Integer.parseInt(thoseSplittedDots[i]);
			if(thisNumber > thatNumber) {
				return 1;
			}
			if(thatNumber > thisNumber) {
				return -1;
			}
		}
		
		if(theseSplittedDots.length == thoseSplittedDots.length) { 
			return 0;
		}
		
		if(theseSplittedDots.length - thoseSplittedDots.length > 0) {
			return 1;
		} else {
			return -1;
		}
	}

	@Override
	public EntityDto<Package> createDto() {
		return new RPackageDto(this);
	}
}
