api_token:
  secret: SecretKeyToGenJWTs

declarative: false

repository-snapshots: true

app:
  authentication: ldap
  ldap:
    url: ldap://oa-rdepot-ldap:389
    basedn: dc=example,dc=org
    userou: 
    loginfield: cn
    namefield:
      - givenName
      - sn
    emailfield: mail
    default:
      admins: einstein 

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  
# Email related properties
spring:
  mail:
    enabled: true
    password: mysecretpassword
    username: rdepot
    host: 192.168.49.1
    port: 3925

# Enable Liquibase  
  liquibase:
    user: postgres
    enabled: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE
