version: '3'
services:
  proxy:
    image: registry.openanalytics.eu/proxy/library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: always
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/rdepot:/etc/nginx/sites-enabled/rdepot:ro
      - repository:/opt/rdepot/repo/:ro
    ports:
      - 8017:80
    depends_on:
      - app
      - repo
    networks:
      - oa-rdepot
      
  app:
    build: ./docker/app
    restart: always
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - ./docker/app/test_configs/test_declarative_config.yml:/opt/rdepot/application.yml  
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro
    ports:
      - 8001:8001
      - 8018:8080
      - 8019:8001
    depends_on:
      - db
      - repo
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/declarative
      - DB_USERNAME=postgres
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 50 
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.23  
      
  repo:
    build: ./docker/repo
    restart: always
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - ./docker/repo/rdepot-repo.jar:/opt/repo/rdepot-repo.jar:ro
      - repository:/opt/rdepot/
      - ./itestServer:/opt/testServer
    networks:
      - oa-rdepot 
        
  db:
    image: registry.openanalytics.eu/proxy/library/postgres:alpine
    restart: always
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/initial_scripts/:/docker-entrypoint-initdb.d/:ro
      - ./docker/db/sql_files/:/opt/sql_files/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 54321:5432  
    networks:
      - oa-rdepot
                            
  ldap:
    build: ./docker/ldap
    restart: unless-stopped
    hostname: oa-rdepot-ldap
    container_name: oa-rdepot-ldap
    environment:
      - LDAP_TLS=false
      - LDAP_ORGANISATION=Test Company
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=testpassword 
    networks:
      - oa-rdepot                      
                  
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:

