version: '3'
services:
  proxy:
    image: registry.openanalytics.eu/proxy/library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: always
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - repository:/opt/rdepot/repo/:ro
    ports:
      - 8017:80
      - 8021:90
      - 8023:95
    depends_on:
      - app
      - repo
      - app-declarative
    networks:
      - oa-rdepot      
      
  repo:
    image: registry.openanalytics.eu/openanalytics/rdepot-repo-it:1.7.5
    restart: always
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - ./docker/repo/rdepot-repo.jar:/opt/repo/rdepot-repo.jar:ro
      - repository:/opt/rdepot/
      - ./itestServer:/opt/testServer
    networks:
      - oa-rdepot 
        
  db:
    image: registry.openanalytics.eu/proxy/library/postgres:alpine
    restart: always
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/initial_scripts/:/docker-entrypoint-initdb.d/:ro
      - ./docker/db/sql_files/:/opt/sql_files/:ro
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - oa-rdepot
                      
  openid:
    image: registry.openanalytics.eu/proxy/qlik/simple-oidc-provider:0.2.4
    restart: unless-stopped
    hostname: oa-rdepot-openid
    container_name: oa-rdepot-openid
    environment:
      - CONFIG_FILE=/opt/rdepot/config.json
      - USERS_FILE=/opt/rdepot/users.json
    volumes:
      - ./docker/oidc/test-config.json:/opt/rdepot/config.json
      - ./docker/oidc/users.json:/opt/rdepot/users.json  
    ports:
      - 9000:9000
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.16
  
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    restart: unless-stopped
    hostname: oa-rdepot-keycloak
    container_name: oa-rdepot-keycloak
    ports:
      - 8080:8080
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=testpassword
      - KEYCLOAK_IMPORT=/opt/rdepot/realm-rdepot.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
     - ./docker/keycloak/test-realm-rdepot.json:/opt/rdepot/realm-rdepot.json
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.17
 
  ldap:
    image: registry.openanalytics.eu/openanalytics/rdepot-ldap-it:1.7.5
    restart: unless-stopped
    hostname: oa-rdepot-ldap
    container_name: oa-rdepot-ldap
    environment:
      - LDAP_TLS=false
      - LDAP_ORGANISATION=Test Company
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=testpassword 
    networks:
      - oa-rdepot
      
  app:    
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - ./docker/app/test_configs/test_ldap_config.yml:/opt/rdepot/application.yml      
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro    
    ports:
      - 8001:8001
      - 8018:8080
      - 8019:8001
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=postgres
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100 
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.21      
  app-without-snapshots:
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-app-without-snapshots
    container_name: oa-rdepot-app-without-snapshots
    volumes:
      - ./docker/app/test_configs/test_ldap_config_snapshots_off.yml:/opt/rdepot/application.yml
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=postgres
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.26
                        
  app-openid:
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-app-openid
    container_name: oa-rdepot-app-openid
    volumes:
      - ./docker/app/test_configs/test_openid_config.yml:/opt/rdepot/application.yml   
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro
    depends_on:
      - db
      - openid
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=postgres
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100 
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.22  
  
  app-keycloak:    
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-app-keycloak
    container_name: oa-rdepot-app-keycloak
    volumes:
      - ./docker/app/test_configs/test_keycloak_config.yml:/opt/rdepot/application.yml
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro        
    depends_on:
      - db
      - keycloak
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=postgres
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.23   
      
  app-simple:
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-app-simple
    container_name: oa-rdepot-app-simple
    volumes:
      - ./docker/app/test_configs/test_simple_config.yml:/opt/rdepot/application.yml
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro        
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=postgres
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100  
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.24   
          
  app-declarative:
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-declarative
    container_name: oa-rdepot-declarative
    volumes:
      - ./docker/app/test_configs/test_declarative_config.yml:/opt/rdepot/application.yml   
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro    
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/declarative
      - DB_USERNAME=postgres      
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 100 
    networks:
      - oa-rdepot
      
  app-migrations:
    image: registry.openanalytics.eu/openanalytics/rdepot-app-it:1.7.5
    restart: always
    hostname: oa-rdepot-migrations
    container_name: oa-rdepot-migrations
    volumes:
      - ./docker/app/test_configs/test_migration.yml:/opt/rdepot/application.yml   
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro    
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/migrations
      - DB_USERNAME=postgres      
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 400 
    networks:
      - oa-rdepot
  
  selenium-chrome:
    image: registry.openanalytics.eu/proxy/selenium/standalone-chrome
    container_name: oa-rdepot-selenium-chrome
    hostname: oa-rdepot-selenium-chrome
    ports:
      - 4444:4444
    networks:
      - oa-rdepot   
 
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
